name: TF Apply

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUB_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}


on:
  push:
    branches:
      - main
jobs:
  job2:
    runs-on: ubuntu-latest
    name: Apply Terraform Plan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Commit
        run: |
          case "${{ github.event.head_commit.message}}" in
            *"rg1"*)
              echo "Setting TF_KEY and SRC to match rg1 case"
              echo "TF_KEY=${{ secrets.AZURE_RG1_KEY }}" >> $GITHUB_ENV
              echo "Making PATH"
              echo "SRC_PATH=rg1" >> $GITHUB_ENV
              echo "Finished"
              ;;
            *"rg2"*)
              echo "Setting TF_KEY and SRC to match rg2 case"
              echo "TF_KEY=${{ secrets.AZURE_RG2_KEY }}" >> $GITHUB_ENV
              echo "Making PATH"
              echo "SRC_PATH=rg2" >> $GITHUB_ENV
              echo "Finished"
              ;;
            *)
              echo "false"
              exit 1
              ;;
          esac
      - name: terraform apply
        uses: azurenoops/terraform-github-actions/terraform-apply@v1.34.2
        with: 
          path: ${{ env.SRC_PATH}}
          backend_config: |
                        resource_group_name=${{ secrets.AZURE_RG }}
                        storage_account_name=${{ secrets.AZURE_SA }}
                        container_name=${{ secrets.AZURE_SC }}
                        key=${{ env.TF_KEY }}